server {
    root www/;
    listen localhost:8080;
    server_name example.com;
    client_max_body_size 1M;
    error_page 404 www/html/errors/default.html;
    error_page 500 /errors/50x.html;

    location / {
        methods GET;
    }

    location /post_body {
        methods POST;
        client_max_body_size 100M;
        upload_dir www/uploads;
    }

    location /directory/ {
        methods GET;
        root YoupiBanane/;
        index youpi.bad_extension;
    }

    location /cgi-bin {
        methods GET POST;
        root /www/cgi-bin;
        cgi_ext .py /usr/bin/python3;
    }
}
