server {
    listen       8080;
    host         127.0.0.1;
    server_name  localhost;
    root         ./www;
    index        index.html;
    client_max_body_size 1m;

    error_page 404 /404.html;

    location / {
        allowed_methods GET POST;
        autoindex       off;
    }
}
