server {
    listen 0.0.0.0:8080;
    root /www;
    client_max_body_size 1M;
    location /upload {
        methods POST;
        upload_dir /www/upload;
    }
    location / {
        root /www;
        methods GET;
    }
}