name: T1.1 - Scaffolding & epoll Skeleton

on:
  pull_request:
    branches: [ main ]

jobs:
  Task_1-1_Testing:
    name: Task 1.1 testing
    runs-on: ubuntu-latest
    outputs:
      matches: ${{ steps.check.outputs.matches }}
    steps:
      - name: Validate PR Title
        id: check
        run: |
          TITLE="${{ github.event.pull_request.title }}"

          if ! echo "$TITLE" | grep -qE "^T[0-9]\.[0-9]*"; then
            echo "FAIL: PR title does not match the required format 'T[sprint].[task] - [description]'"
            exit 1
          fi

          PR_SPRINT=$(echo "$TITLE" | grep -oP "^T\K[0-9]+(?=\.)")

          SPRINT=1
          TASK=1

          if [ "$PR_SPRINT" -gt "$SPRINT" ]; then
            echo "matches=true" >> $GITHUB_OUTPUT
          elif echo "$TITLE" | grep -qE "^T${SPRINT}\.${TASK}\s*[-—]"; then
            echo "matches=true" >> $GITHUB_OUTPUT
          else
            echo "matches=false" >> $GITHUB_OUTPUT
          fi
        
      - uses: actions/checkout@v4
      
      #────── BUILD
      - name: Compile with strict flags
        run: make
      
      - name: Verify binary exists
        run: test -f ./webserv && echo "Binary exists"
      
      #──── MAKEFILE
      
      - name: make all
        run: make all

      - name: make clean - removes object
        run: |
          make clean
          find . -name "*.o" | grep -q . && echo "FAIL: .o files remain" && exit 1
          echo "PASS: no .o files after clean"
      
      - name: make fclean - removes binary
        run: |
          make fclean
          test ! -f ./webserv && echo "PASS: binary removed!"
      
      - name: make re - full rebuild
        run: |
          make
          OUTPUT=$(make 2>&l)
          echo "$OUTPUT" | grep -q "Nothing to be done for" && echo "PASS: no relink" || (echo "FAIL: relinking" && exit 1)

      # ── C++98 Compliance ──
      - name: Check for auto keyword
        run: |
          grep -rn "\bauto\b" src/ includes/ && echo "FAIL: 'auto' found" && exit 1
          echo "PASS: no auto"

      - name: Check for nullptr
        run: |
          grep -rn "\bnullptr\b" src/ includes/ && echo "FAIL: 'nullptr' found" && exit 1
          echo "PASS: no nullptr"

      - name: Compile explicitly with -std=c++98
        run: make fclean && make CXXFLAGS="-Wall -Wextra -Werror -std=c++98"
